#!/usr/bin/env bash
# aurpac wraps cloning an AUR repo and makepkg into one command,
# and cleans up the AUR repo afterwards

# temporary build directory
DIR=aurpacs_temporary_arch_user_repository_directory

# Colored output so it looks nice
ERROR='\033[1;31m'   # red
SUCCESS='\033[1;32m' # green
INFO='\033[1;34m'    # blue
WHITE='\033[1;37m'   # white
RESET='\033[0m'      # text color reset

aurpac_msg() {
    echo -e "${WHITE}[${1}aurpac${WHITE}]${RESET} ${2}"
}

if [ $# -ne 1 ]; then
    aurpac_msg $ERROR "Illegal number of arguments, expected 1, got $#"
    exit 1
fi

if [ -d $DIR ]; then
    aurpac_msg $INFO "Cleaning old temporary directory..."
    rm -rf $DIR
fi

mkdir $DIR && cd $DIR
aurpac_msg $INFO "Cloning repository..."


if ! git ls-remote --exit-code "https://aur.archlinux.org/$1.git" > /dev/null; then
    aurpac_msg $ERROR "Git repository is empty, check if there's a typo"
    exit 1
fi

git clone "https://aur.archlinux.org/$1.git" . --quiet

if makepkg -sic; then
    cd .. && rm -rf $DIR
    aurpac_msg $INFO "Done!"
else
    aurpac_msg $ERROR "Failed to build package"
fi
