#!/usr/bin/env python3

import fire

def shear_flow(shear, Q, I):
    ''' Calculate the shear flow in a member '''
    q = (shear * Q) / I
    print("Shear Flow: {:.6e}".format(q))

def Q(na, base, height):
    ''' Calculate whatever Q is '''
    area = base * height
    q = na * area
    print("Q: {:.6e}".format(q))

def moi(base, height):
    ''' Calculate the moment of inertia '''
    moi = (1 / 12) * base * (height ** 3)
    print("Moment of Inertia: {:.6e}".format(moi))

def sub(val1, val2):
    ''' Subtract two values '''
    answer = val1 - val2
    print("Value: {:.6e}".format(answer))


if __name__ == '__main__':
    fire.Fire()
