#!/usr/bin/env python3
import string
from secrets import choice
from argparse import ArgumentParser


DEFAULT_LEN = 16
parser = ArgumentParser(description="generate a random password, with configurable output")
parser.add_argument("--no-special", action="store_true", help="no special characters in password")
parser.add_argument("--no-upper", action="store_true", help="no uppercase letters in password")
parser.add_argument("--no-lower", action="store_true", help="no lowercase letters in password")
parser.add_argument("--no-numbers", action="store_true", help="no numbers in password")
parser.add_argument("--length", default=DEFAULT_LEN, type=int, help=f"length of the password [default: {DEFAULT_LEN}]")

args = parser.parse_args()

# make sure the user didn't pass in all of the flags
if all(vars(args).values()):
    print("you cannot use all of the flags at once")
    exit(1)

char_set = ""
if not args.no_special:
    char_set += string.punctuation
if not args.no_upper:
    char_set += string.ascii_uppercase
if not args.no_lower:
    char_set += string.ascii_lowercase
if not args.no_numbers:
    char_set += string.digits

password = "".join(choice(char_set) for _ in range(args.length))
print(password)
