#!/usr/bin/env python3

"""
Run a bunch of different programs depending on the
type of file passed to run.
"""

import os
import sys
import fire


def run_file(filename):
    ''' Call the correct program given a file's extension. '''
    # get file extension without the dot
    commands = {
        'py': 'python3 ',
        'm': 'matlab -nojvm -nodisplay -nosplash -r '
    }
    try:
        file_ext = filename.split('.')[1]
        command = commands[file_ext]
    except KeyError:
        print(f"File of type '*.{file_ext}' is not supported.")
        sys.exit(1)
    except IndexError:
        print(f"Can't run executable '{filename}'.")
        sys.exit(1)
    os.system(command + filename)


if __name__ == "__main__":
    fire.Fire(run_file, name="run")
