#!/usr/bin/env python3

"""
Run a bunch of different programs depending on the 
type of file passed to run. 
"""

import os
import sys
import argparse

parser = argparse.ArgumentParser(
    description='Run programs according to their file extension.')

parser.add_argument('file', metavar='FILE', type=str,
                    help="Name of the file that you would like to run")


def main():
    args = parser.parse_args()
    filename = args.file
    # get file extension without the dot
    command = get_command(filename.split('.')[1])
    os.system(command + filename)


def get_command(file_ext):
    commands = {
        'py': 'python3 ',
        'm': 'octave -q --no-gui '
    }
    try:
        command = commands[file_ext]
        return command
    except KeyError:
        print(f"File of type '*.{file_ext}' is not supported.")
        sys.exit(1)


if __name__ == "__main__":
    main()
